layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: hellresistor
  # unsplash: your_username
  # vk: your_username
  website: http://hellresistor.github.io
  # youtube: your_username

topics:
  - name: Bash
    web_url: https://github.com/topics/bash
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/bash/bash.png
  - name: HA
    web_url: https://github.com/home-assistant
    image_url: https://avatars.githubusercontent.com/u/13844975?s=200&v=4
  - name: Bitcanna
    web_url: https://github.com/BitCannaGlobal
    image_url: https://avatars.githubusercontent.com/u/39583369?v=4
